routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('register', 'UsersController@create')->name('register');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

// Default Routes
Route::get('/', 'ProductsController@shop')->name('index');
Route::get('home', 'HomeController@appIndex')->name('home');
Route::get('status/all', 'StatusController@all')->name('status.all');
Route::get('categories/all', 'CategoriesController@all')->name('categories.all');

Route::get('products/desc/{id}', 'ProductsController@desc')->name('products.desc');
Route::get('products/shop', 'ProductsController@shop')->name('products.shop');
Route::get('products/find/{id}', 'ProductsController@find')->name('products.find');
Route::get('products/all', 'ProductsController@all')->name('products.all');

Route::post('users', 'UsersController@store')->name('users.store');

// Admin Routes
Route::group(['middleware' => ['auth', 'can:access-admin']], function () {
	// Attributes
	Route::get('attributes/create/{product_id}', 'AttributesController@create')->name('attributes.create');
	Route::get('attributes/edit/{id}', 'AttributesController@edit')->name('attributes.edit');

	// Categories
	Route::get('categories/edit/{id}', 'CategoriesController@edit')->name('categories.edit');

	// Products
	Route::put('products/image/pull/{id}/{index}', 'ProductsController@pullImage')->name('products.image.pull');
	Route::put('products/image/push/{id}/{index}', 'ProductsController@pushImage')->name('products.image.push');
	Route::post('products/image/{id}', 'ProductsController@uploadImage')->name('products.image.upload');
	Route::delete('products/image/{id}/{index}', 'ProductsController@deleteImage')->name('products.image.delete');

	// Resources
	Route::resource('attributes', 'AttributesController')->except(['index','show','create','edit']);
	Route::resource('categories', 'CategoriesController')->only(['create','store','update']);
	Route::resource('products', 'ProductsController');
});

// Authenticated Routes
Route::group(['middleware' => ['auth']], function () {
	Route::get('users/find/{id}', 'UsersController@find')->name('users.find');
	Route::get('users/all', 'UsersController@all')->name('users.all');

	// Orders
	Route::get('orders/home/{id}', 'OrdersController@home')->name('orders.home');
	Route::get('orders/cart', 'OrdersController@cart')->name('orders.cart');
	Route::get('orders/current', 'OrdersController@current')->name('orders.current');
	Route::get('orders/delivery', 'OrdersController@delivery')->name('orders.delivery');
	Route::get('orders/payment', 'OrdersController@payment')->name('orders.payment');
	Route::get('orders/payment/billet', 'OrdersController@billet')->name('orders.payment.billet');
	Route::get('orders/payment/card', 'OrdersController@card')->name('orders.payment.card');
	Route::get('orders/checkout', 'OrdersController@checkout')->name('orders.checkout');
	Route::get('orders/checkout/success/{id}', 'OrdersController@success')->name('orders.checkout.success');
	Route::get('orders/card/create', 'OrdersController@cardCreate')->name('orders.card.create');
	Route::get('orders/find/{id}', 'OrdersController@find')->name('orders.find');
	Route::get('orders/form/address', 'OrdersController@formAddress')->name('orders.form.address');
	Route::get('orders/delivery/cost', 'OrdersController@calcDeliveryCost')->name('orders.delivery.cost');
	Route::put('orders/item/method', 'OrdersController@changeItemMethod')->name('orders.item.method.change');
	Route::put('orders/item/installment', 'OrdersController@changeItemInstallment')->name('orders.item.installment.change');
	Route::post('orders/checkout', 'OrdersController@postCheckout')->name('orders.checkout.post');
	Route::post('orders/item/{product_id}', 'OrdersController@addItem')->name('orders.item.add');
	Route::post('orders/address', 'OrdersController@storeAddress')->name('orders.address.store');
	Route::post('orders/payment/select_card', 'OrdersController@selectCard')->name('orders.payment.select_card');

	// Items
	Route::post('items/store', 'ItemsController@store')->name('items.store');
	Route::post('items/increase/{id}', 'ItemsController@increase')->name('items.increase');
	Route::post('items/decrease/{id}', 'ItemsController@decrease')->name('items.decrease');
	Route::delete('items/destroy/{id}', 'ItemsController@destroy')->name('items.destroy');

	// Cards
	Route::get('cards/all', 'CardsController@all')->name('cards.all');
	Route::get('cards/edit/{id}', 'CardsController@edit')->name('cards.edit');

	// Resources
	Route::resource('cards', 'CardsController')->only(['create','store','update']);
	Route::resource('orders', 'OrdersController');
	Route::resource('users', 'UsersController')->except('store');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;
use Illuminate\Support\Facades\Storage;
use Folklore\Image\Facades\Image;
use App\Models\Attribute;

/**
 * Class Product.
 *
 * @package namespace App\Models;
 */
class Product extends Model implements Transformable {
	use TransformableTrait;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'name',
		'description',
		'category_id',
		'value_partner',
		'value_seller',
		'weight',
		'height',
		'width',
		'length',
		'diameter',
		'quantity',
		'interest_free',
		'free_shipping',
		'status'
	];

	protected $appends = ['files', 'thumbnails', 'value'];
	protected $with = ['attributes', 'category'];

	public function attributes(){
		return $this->hasMany(Attribute::class);
	}

	public function category(){
		return $this->belongsTo(Category::class);
	}

	public function getFilesAttribute(){
		$path = env('FILES_PATH_PRODUCTS')."/".$this->id."/";
		$files = Storage::files($path);
		foreach ($files as $key => $file) {
			$files[$key] = '/'.str_replace("public", 'storage', $file);
		}
		return $files;
	}

	public function getThumbnailsAttribute(){
		$files = [];
		foreach ($this->files as $key => $file) {
			$files[$key] = Image::url($file,300,300,array('crop'));
		}
		return $files;
	}

	public function getValueAttribute(){
		return $this[\App\Helpers\PermHelper::lowerValueText()];
	}

}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\ProductRepository;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;

/**
 * Class ProductsController.
 *
 * @package namespace App\Http\Controllers;
 */
class ProductsController extends Controller {

	protected $repository;

	public function __construct(ProductRepository $repository) {
		$this->repository = $repository;
		$this->names = [
			'plural' => 'products',
			'singular' => 'product',
			'pt_plural' => 'produtos',
			'pt_singular' => 'produto',
			'pt_gender' => 'o',
			'base_blades' => 'products'
		];
	}

	/**
	 * Disponible methods from Trait.
	 */
	use ControllerTrait {
		ControllerTrait::trait_index as index;
		ControllerTrait::trait_desc as desc;
		ControllerTrait::trait_show as show;
		ControllerTrait::trait_create as create;
		ControllerTrait::trait_edit as edit;
		ControllerTrait::trait_store as store;
		ControllerTrait::trait_update as update;
		ControllerTrait::trait_find as find;
		ControllerTrait::trait_all as all;
	}

	/**
	 * Display a listing of the resource.
	 */
	public function shop() {
		$this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
		$products = $this->repository->all();

		return view('app.products.shop', compact('products'));
	}

	/**
	 * Delete specific image from Product.
	 */
	private function deleteAllImages($id){
		$path = env('FILES_PATH_PRODUCTS')."/".$id."/";
		$files = Storage::files($path);
		foreach ($files as $file) {
			Storage::delete($file);
		}
	}

	/**
	 * Delete specific image from Product.
	 */
	public function deleteImage($id, $index){
		$path = env('FILES_PATH_PRODUCTS')."/".$id."/";
		$files = Storage::files($path);
		Storage::delete($files[$index]);
		$this->refreshImageNames($id);
		return response()->json([
			'message' => 'Imagem removida'
		]);
	}

	/**
	 * Upload specific image to Product.
	 */
	public function uploadImage(Request $request, $id){
		$path = env('FILES_PATH_PRODUCTS')."/".$id."/";
		foreach ($request->file('fileInput') as $key => $file) {
			$files = Storage::files($path);
			$store = Storage::putFileAs($path, $file, count($files)."_".date('YmdHis').".".$file->getClientOriginalExtension());
		}
		return response()->json([
			'message' => 'Imagens atualizadas'
		]);
	}

	/* Altera o indice da imagem */
	public function pullImage(Request $request, $id, $index){
		$path = env('FILES_PATH_PRODUCTS')."/".$id."/";
		$files = Storage::files($path);
		$minIndex = $index < 1 ? 0 : $index-1;
		Storage::move($files[$index], $path.$minIndex.".".File::extension($files[$index]));
		$this->refreshImageNames($id);
		return response()->json([
			'message' => 'Imagem atualizada'
		]);
	}

	/* Altera o indice da imagem */
	public function pushImage(Request $request, $id, $index){
		$path = env('FILES_PATH_PRODUCTS')."/".$id."/";
		$files = Storage::files($path);
		$newIndex = $index+1;
		Storage::move($files[$index], $path.$newIndex."_99999999999999.".File::extension($files[$index]));
		$this->refreshImageNames($id);
		return response()->json([
			'message' => 'Imagem atualizada.'
		]);
	}

	private function refreshImageNames($id){
		$path = env('FILES_PATH_PRODUCTS')."/".$id."/";
		$files = Storage::files($path);
		foreach ($files as $key => $file) {
			Storage::move($file, $path.$key."_".date('YmdHis').".".File::extension($file));
		}
		return true;
	}
}

resources/views/app/products/_form.blade.php
<div class="row">
	<div class="col-8">
		<div class="form-label-group">
			<input type="text" class="form-control" id="prod_name" name="prod_name" placeholder="Nome" v-model="product.name" required>
			<label for="prod_name">Nome</label>
		</div>
	</div>
	<div class="col-4">
		<div class="form-label-group">
			<select class="form-control float-label-select" id="prod_category" name="prod_category" v-model="product.category_id">
				<option value selected></option>
				<option v-for="category in categories" :value="category.id">@{{ category.name }}</option>
			</select>
			<label for="prod_category">Categoria</label>
		</div>
	</div>
</div>
<div class="row">
	<div class="col">
		<div class="input-group appends">
			<div class="form-label-group form-control">
				<input type="number" step="1" class="form-control" id="prod_height" name="prod_height" placeholder="Altura" v-model="product.height">
				<label for="prod_height">Altura</label>
			</div>
			<div class="input-group-append">
				<div class="input-group-text">Cm</div>
			</div>			
		</div>
	</div>
	<div class="col">
		<div class="input-group appends">
			<div class="form-label-group form-control">
				<input type="number" step="1" class="form-control" id="prod_width" name="prod_width" placeholder="Largura" v-model="product.width">
				<label for="prod_width">Largura</label>
			</div>
			<div class="input-group-append">
				<div class="input-group-text">Cm</div>
			</div>			
		</div>
	</div>
	<div class="col">
		<div class="input-group appends">
			<div class="form-label-group form-control">
				<input type="number" step="1" class="form-control" id="prod_length" name="prod_length" placeholder="Comprimento" v-model="product.length">
				<label for="prod_length">Comprimento</label>
			</div>
			<div class="input-group-append">
				<div class="input-group-text">Cm</div>
			</div>			
		</div>
	</div>
</div>
<div class="row">
	<div class="col">
		<div class="input-group appends">
			<div class="form-label-group form-control">
				<input type="number" step="0.01" class="form-control" id="prod_weight" name="prod_weight" placeholder="Peso" v-model="product.weight">
				<label for="prod_weight">Peso</label>
			</div>
			<div class="input-group-append">
				<div class="input-group-text">Kg</div>
			</div>
		</div>
	</div>
	<div class="col">
		<div class="input-group appends">
			<div class="form-label-group form-control">
				<input type="number" step="1" class="form-control" id="prod_diameter" name="prod_diameter" placeholder="Diâmetro" v-model="product.diameter">
				<label for="prod_diameter">Diâmetro</label>
			</div>
			<div class="input-group-append">
				<div class="input-group-text">Cm</div>
			</div>			
		</div>
	</div>
</div>
<div class="row">
	<div class="col">
		<div class="input-group appends">
			<div class="input-group-prepend">
				<div class="input-group-text">R$</div>
			</div>
			<div class="form-label-group form-control">
				<input type="number" step="0.01" class="form-control" id="prod_value_seller" name="prod_value_seller" placeholder="Valor - Vendedor" v-model="product.value_seller">
				<label for="prod_value_seller">Valor - Vendedor</label>
			</div>
		</div>
	</div>
	<div class="col">
		<div class="input-group appends">
			<div class="input-group-prepend">
				<div class="input-group-text">R$</div>
			</div>
			<div class="form-label-group form-control">
				<input type="number" step="0.01" class="form-control" id="prod_value_partner" name="prod_value_partner" placeholder="Valor - Parceiro" v-model="product.value_partner">
				<label for="prod_value_partner">Valor - Parceiro</label>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-6">
		<div class="form-group">
			<div class="btn-group btn-group-toggle border rounded d-flex" role="group" data-toggle="buttons" style="width: 100%; height: 49px;">
				<label class="btn btn-light w-100" :class="{active : product.free_shipping == '1'}" style="padding-top:12px;">
					<input type="radio" name="prod_free_shipping" table="product" field="free_shipping" autocomplete="off" v-model="product.free_shipping" value="1" required>Frete Grátis
				</label>
				<label class="btn btn-light w-100" :class="{active : product.free_shipping == '0'}" style="padding-top:12px;">
					<input type="radio" name="prod_free_shipping" table="product" field="free_shipping" autocomplete="off" v-model="product.free_shipping" value="0" required>Frete Pago
				</label>
			</div>
		</div>
	</div>
	<div class="col-6">
		<div class="form-label-group">
			<select class="form-control float-label-select" id="prod_interest_free" name="prod_interest_free" v-model="product.interest_free" required>
				<option value selected disabled></option>
				<option value="1">1</option>
				<option value="6">6</option>
				<option value="12">12</option>
			</select>
			<label for="prod_interest_free">Parcelas Sem juros</label>
		</div>
	</div>
</div>
<div class="row">
	<div class="col">
		<div class="form-label-group">
			<textarea rows="4" class="form-control" id="prod_description" name="prod_description" placeholder="Descrição" v-model="product.description" required></textarea>
			<label for="prod_description">Descrição</label>
		</div>
	</div>
</div>

resources/views/app/products/create.blade.php
<div>
	<div id="productCreateApp">
		<h2 class="page-title">Produto <small> | Cadastro de novo Produto</small></h2>
		<form action="" id="formCreateProduct">

			@include('app.products._form')

			<div class="row">
				<div class="col-sm-12">
					<div class="form-group">
						<button class="btn btn-success float-right" @click.prevent="submitFormCreateProduct" title="Salvar">{!! ICONS_OK !!}</i></button>
						<button type="button" class="btn btn-danger float-left closeFancybox" title="Cancelar">{!! ICONS_CANCEL !!}</i></button>
					</div>
				</div>
			</div>
		</form>
	</div>

	<script type="text/javascript">
		new Vue({
			el: '#productCreateApp',
			data: {
				product: {
					_token: "{{ csrf_token() }}"
				},
				categories: []
			},
			created: function(){
				var self = this;
				$.get('{{ route('categories.all') }}', function(data) {
					self.categories = data;
				});
			},
			methods:{
				submitFormCreateProduct: function (){ 
					var self = this;
					validaForm("#formCreateProduct", function(){
						$.post('{{ route('products.store') }}', self.product, function(data) {	
							if(data.error){
								toastr.error('Falha ao criar produto!');
							}else{
								toastr.success('Produto criado com sucesso');
							}
							parent.jQuery.fancybox.close();
						});
					});
					$("#formCreateProduct").submit();
				}
			}
		});
	</script>
</div>

resources/views/app/products/edit.blade.php
<div>
	<div id="productEditApp">
		<h2 class="page-title">Produto <small> | Edição de Produto</small></h2>
		<form action="" id="formEditProduct">

			@include('app.products._form')

			<div class="row">
				<div class="col-sm-12">
					<div class="form-group">
						<button class="btn btn-success float-right" @click.prevent="submitFormEditProduct" title="Salvar">{!! ICONS_OK !!}</i></button>
						<button type="button" class="btn btn-danger float-left closeFancybox" title="Cancelar">{!! ICONS_CANCEL !!}</i></button>
					</div>
				</div>
			</div>
		</form>
	</div>

	<script type="text/javascript">
		new Vue({
			el: '#productEditApp',
			data: {
				product: {!! $product->toJson() !!},
				categories: []
			},
			created: function(){
				var self = this;
				$.get('{{ route('categories.all') }}', function(data) {
					self.categories = data;
				});
			},
			updated: function(){
				$("select").trigger('change');
			},
			methods:{
				submitFormEditProduct: function (){ 
					var self = this;
					validaForm("#formEditProduct", function(){
						self.product._token = "{{ csrf_token() }}";
						$.put('{{ route('products.update', [$product->id]) }}', self.product, function(data) {
							if(data.error){
								toastr.error('Falha ao atualizar produto!');
							}else{
								toastr.success('Produto atualizado com sucesso');
							}
							parent.jQuery.fancybox.close();
						});
					});
					$("#formEditProduct").submit();
				}
			}
		});
	</script>
</div>

resources/views/app/products/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="page-title pb-3">
		<h3>
			Produtos | <small class="text-muted">Listagem de Produtos cadastrados</small>
			<button type="button" class="btn btn-sm btn-primary float-right" title="Novo Produto" onclick="openFormProduct()">{!! ICONS_ADD !!}</button>
		</h3>
	</div>
	<div class="row justify-content-center">
		<div class="col">
			<div class="card">
				<div class="card-body">
					<table id="table-products" class="table table-striped table-hover table-pointer">
						<thead>
							<tr>
								<th>Nome</th>
								<th>Valores</th>
								<th>Status</th>
								<th>Imagens</th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>Nome</th>
								<th>Valores</th>
								<th>Status</th>
								<th>Imagens</th>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		$(document).ready(function() {
			$('#table-products').DataTable({
				ajax: {
					url: "{{ route('products.all') }}",
					dataSrc: ""
				},
				columns: [
					{ data: function(data){ return filters.name(data.name); }},
					{ data: function(data){ return filters.currency(data.value_seller, true)+" / "+filters.currency(data.value_partner, true); }},
					{ data: function(data){ return filters.yn(data.status); }},
					{ data: function(data){ return data.files.length; }}
				],
				processing: true,
				order: [],
				fnRowCallback: function( row, data, index, indexFull ) {
					$(row).on('click', function(evt) {
						window.open("{{ route('products.show', ['']) }}/"+data.id, evt.ctrlKey ? '_blank' : '_self');
					});
				}
			});
		});

		function openFormProduct(){
			$.fancybox.open({
				src: '{{ route('products.create') }}',
				type: 'ajax',
				opts: { 
					clickOutside: false,
					clickSlide: false,
					afterClose : function(){
						$('#table-products').DataTable().ajax.reload(null, false); 
					},
				}
			});
		}
	</script>
@endsection

resources/views/app/products/show.blade.php
@extends('layouts.app')

@section('content')
	<div id="productShowApp">
		<div class="page-title">
			<h3>
				Produtos | <small class="text-muted">Descrição do produto</small>
				<button type="button" class="btn btn-sm btn-primary float-right" title="Editar Produto" @click="openFormEditProduct()">{!! ICONS_EDIT !!}</button>
			</h3>
		</div>
		<div class="row justify-content-center">
			<div class="col-sm-3">
				<div class="card">
					<div class="card-body">
						<div class="row justify-content-center">
							<div class="col-10">
								<img v-if="product.files.length > 0" :src="product.thumbnails[0]" class="img-fluid img-thumbnail rounded-circle">
								<img v-else src="{{ DEFAULT_IMAGE_PRODUCTS }}" class="img-fluid img-thumbnail rounded-circle">
							</div>
						</div>
						<div class="row">
							<div class="col">
								<hr>
							</div>
						</div>
						<div class="row">
							<div class="col">
								<label class="label-plaintext label-sm" for="prod_id">Id:</label>
								<p class="form-control-plaintext" id="prod_id">@{{ product.id | default }}</p>
							</div>
						</div>
						<div class="row">
							<div class="col">
								<label class="label-plaintext label-sm" for="prod_name">Nome:</label>
								<p class="form-control-plaintext" id="prod_name">@{{ product.name | name }}</p>
							</div>
						</div>
						<div class="row">
							<div class="col">
								<label class="label-plaintext label-sm" for="prod_categ_name">Categoria:</label>
								<p class="form-control-plaintext" id="prod_categ_name" v-if="product.category">@{{ product.category.name | name }}</p>
								<p class="form-control-plaintext" id="prod_categ_name" v-else>-</p>
							</div>
						</div>
						<div class="row">
							<div class="col">
								<label class="label-plaintext label-sm" for="prod_value">Valor:</label>
								<p class="form-control-plaintext" id="prod_value">
									@{{ product.value_seller | currency(true) }} 
									@if(\App\Helpers\PermHelper::viewValues()) 
										/ @{{ product.value_partner | currency(true) }}
									@endif
								</p>
							</div>
						</div>
						<div class="row">
							<div class="col">
								<label class="label-plaintext label-sm" for="prod_value">Medidas: <small>(P | D | AxLxC)</small></label>
								<p class="form-control-plaintext" id="prod_value">@{{ product.weight }}Kg | @{{ product.diameter }}cm | @{{ product.height }}x@{{ product.width }}x@{{ product.length }}cm</p>
							</div>
						</div>
						<div class="row">
							<div class="col">
								<label class="label-plaintext label-sm" for="prod_description">Descrição:</label>
								<p class="form-control-plaintext" id="prod_description">@{{ product.description | default }}</p>
							</div>
						</div>
						<div class="row att_overlay rounded" v-if="product.attributes" v-for="attribute in product.attributes" @click="openFormEditAttribute(attribute.id)">
							<div class="col">	
								<label class="label-plaintext label-sm">@{{ attribute.name | name }}:</label>
								<p class="form-control-plaintext">@{{ attribute.value | default }}</p>
							</div>
						</div>
						<button type="button" class="btn btn-sm btn-primary float-right" title="Adicionar Atributo" @click="openFormAddAttribute()">{!! ICONS_ADD !!}</button>
					</div>
				</div>
			</div>
			<div class="col-sm-9">
				<div class="card">
					<div class="card-body">
						<div class="col">
							<div class="row" v-if="product.files.length > 0">
								<div class="col-xs-6 col-md-6 col-lg-4 col-xl-3" style="padding: 10px;" v-for="(file, key) in product.files">
									<div class="bs_hovereffect rounded">
										<img :src="product.thumbnails[key]" class="img-fluid img-thumbnail rounded">
										<div class="overlay">
											<div class="rotate text-center">
												<p class="bs_group1">
													<a href="#" @click.prevent="imagePull(product.id, key)" title="Atualizar Imagem">
														{!! ICONS_ARROW_LEFT !!}
													</a>
													<a href="#" @click.prevent="imagePush(product.id, key)" title="Opções da Imagem">
														{!! ICONS_ARROW_RIGHT !!}
													</a>
												</p>
												<hr><hr>
												<p class="bs_group2">
													<a :href="file" data-fancybox="gallery" title="Visualizar Imagem">
														{!! ICONS_SEARCH !!}
													</a>
													<a href="#" @click.prevent="removeFile(product.id, key)" title="Remover Imagem">
														{!! ICONS_REMOVE !!}
													</a>
												</p>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="row" v-else>
								<div class="col text-center">
									<h5>Nenhuma imagem encontrada!<br><small class="text-muted">Adicione novas imagens para visualizá-las aqui.</small></h5>
								</div>
							</div>
						</div>
						<form method="POST" id="formImageUpload" class="d-none">
							<input type="file" name="fileInput[]" id="fileInput" multiple>
							{{ csrf_field() }}
						</form>
						<button type="button" class="btn btn-primary float-right" title="Adicionar Imagens" @click="openFormImage()">{!! ICONS_UPLOAD !!}</button>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		new Vue({
			el: '#productShowApp',
			data: {
				product: {!! $product->toJson() !!}
			},
			mounted: function(){
				var self = this;
				validaForm("#formImageUpload", function() {
					var formData = new FormData($('#formImageUpload')[0]);
					$.ajax({
						url: "{{ route('products.image.upload', [$product->id]) }}",
						type: 'POST',
						success: completeHandler = function(data) { 
							self.reloadData();
						},
						data: formData,
						cache: false,
						contentType: false,
						processData: false,
						async: true
					}, 'json');
				});
				$('#fileInput').change(function(event) {
					if($('#fileInput').val()){
						$('#formImageUpload').submit();
					}
				});
			},
			methods:{
				reloadData: function (){
					var self = this;
					$.get('{{ route('products.find', [$product->id]) }}', function(data) {
						if(data.error){
							toastr.error('Falha ao atualizar produto!');
						}else{
							self.product = data;
						}
					});
				},
				openFormImage: function(){
					$('#fileInput').click();
				},
				openFormEditProduct: function(){
					var self = this;
					$.fancybox.open({
						src: '{{ route('products.edit', [$product->id]) }}',
						type: 'ajax',
						opts: { 
							clickOutside: false,
							clickSlide: false,
							afterClose : function(){
								self.reloadData(); 
							},
						}
					});
				},
				openFormAddAttribute: function(){
					var self = this;
					$.fancybox.open({
						src: '{{ route('attributes.create', [$product->id]) }}',
						type: 'ajax',
						opts: { 
							clickOutside: false,
							clickSlide: false,
							afterClose : function(){
								self.reloadData(); 
							},
						}
					});
				},
				openFormEditAttribute: function(id){
					var self = this;
					$.fancybox.open({
						src: '{{ route('attributes.edit', ['']) }}/'+id,
						type: 'ajax',
						opts: { 
							clickOutside: false,
							clickSlide: false,
							afterClose : function(){
								self.reloadData(); 
							},
						}
					});
				},
				removeFile: function(id, index){
					var self = this;
					$.delete('{{ route('products.image.delete', ['', '']) }}/'+id+'/'+index, { '_token': "{{ csrf_token() }}" }, function(data) {
						toastr.success('Imagem removida com sucesso!');
						self.reloadData();
					});
				},
				imagePull: function(id, index){
					var self = this;
					$.put('{{ route('products.image.pull', ['', '']) }}/'+id+'/'+index, { '_token': "{{ csrf_token() }}" }, function(data) {
						self.reloadData();
					});
				},
				imagePush: function(id, index){
					var self = this;
					$.put('{{ route('products.image.push', ['', '']) }}/'+id+'/'+index, { '_token': "{{ csrf_token() }}" }, function(data) {
						self.reloadData();
					});
				}
			},
			filters: filters
		});
	</script>
@endsection