routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('register', 'UsersController@create')->name('register');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

// Default Routes
Route::get('/', 'ProductsController@shop')->name('index');
Route::get('home', 'HomeController@appIndex')->name('home');
Route::get('status/all', 'StatusController@all')->name('status.all');
Route::get('categories/all', 'CategoriesController@all')->name('categories.all');

Route::get('products/desc/{id}', 'ProductsController@desc')->name('products.desc');
Route::get('products/shop', 'ProductsController@shop')->name('products.shop');
Route::get('products/find/{id}', 'ProductsController@find')->name('products.find');
Route::get('products/all', 'ProductsController@all')->name('products.all');

Route::post('users', 'UsersController@store')->name('users.store');

// Admin Routes
Route::group(['middleware' => ['auth', 'can:access-admin']], function () {
	// Attributes
	Route::get('attributes/create/{product_id}', 'AttributesController@create')->name('attributes.create');
	Route::get('attributes/edit/{id}', 'AttributesController@edit')->name('attributes.edit');

	// Categories
	Route::get('categories/edit/{id}', 'CategoriesController@edit')->name('categories.edit');

	// Products
	Route::put('products/image/pull/{id}/{index}', 'ProductsController@pullImage')->name('products.image.pull');
	Route::put('products/image/push/{id}/{index}', 'ProductsController@pushImage')->name('products.image.push');
	Route::post('products/image/{id}', 'ProductsController@uploadImage')->name('products.image.upload');
	Route::delete('products/image/{id}/{index}', 'ProductsController@deleteImage')->name('products.image.delete');

	// Resources
	Route::resource('attributes', 'AttributesController')->except(['index','show','create','edit']);
	Route::resource('categories', 'CategoriesController')->only(['create','store','update']);
	Route::resource('products', 'ProductsController');
});

// Authenticated Routes
Route::group(['middleware' => ['auth']], function () {
	Route::get('users/find/{id}', 'UsersController@find')->name('users.find');
	Route::get('users/all', 'UsersController@all')->name('users.all');

	// Orders
	Route::get('orders/home/{id}', 'OrdersController@home')->name('orders.home');
	Route::get('orders/cart', 'OrdersController@cart')->name('orders.cart');
	Route::get('orders/current', 'OrdersController@current')->name('orders.current');
	Route::get('orders/delivery', 'OrdersController@delivery')->name('orders.delivery');
	Route::get('orders/payment', 'OrdersController@payment')->name('orders.payment');
	Route::get('orders/payment/billet', 'OrdersController@billet')->name('orders.payment.billet');
	Route::get('orders/payment/card', 'OrdersController@card')->name('orders.payment.card');
	Route::get('orders/checkout', 'OrdersController@checkout')->name('orders.checkout');
	Route::get('orders/checkout/success/{id}', 'OrdersController@success')->name('orders.checkout.success');
	Route::get('orders/card/create', 'OrdersController@cardCreate')->name('orders.card.create');
	Route::get('orders/find/{id}', 'OrdersController@find')->name('orders.find');
	Route::get('orders/form/address', 'OrdersController@formAddress')->name('orders.form.address');
	Route::get('orders/delivery/cost', 'OrdersController@calcDeliveryCost')->name('orders.delivery.cost');
	Route::put('orders/item/method', 'OrdersController@changeItemMethod')->name('orders.item.method.change');
	Route::put('orders/item/installment', 'OrdersController@changeItemInstallment')->name('orders.item.installment.change');
	Route::post('orders/checkout', 'OrdersController@postCheckout')->name('orders.checkout.post');
	Route::post('orders/item/{product_id}', 'OrdersController@addItem')->name('orders.item.add');
	Route::post('orders/address', 'OrdersController@storeAddress')->name('orders.address.store');
	Route::post('orders/payment/select_card', 'OrdersController@selectCard')->name('orders.payment.select_card');

	// Items
	Route::post('items/store', 'ItemsController@store')->name('items.store');
	Route::post('items/increase/{id}', 'ItemsController@increase')->name('items.increase');
	Route::post('items/decrease/{id}', 'ItemsController@decrease')->name('items.decrease');
	Route::delete('items/destroy/{id}', 'ItemsController@destroy')->name('items.destroy');

	// Cards
	Route::get('cards/all', 'CardsController@all')->name('cards.all');
	Route::get('cards/edit/{id}', 'CardsController@edit')->name('cards.edit');

	// Resources
	Route::resource('cards', 'CardsController')->only(['create','store','update']);
	Route::resource('orders', 'OrdersController');
	Route::resource('users', 'UsersController')->except('store');
});

resources/views/app/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-8">
			<div class="card">
				<div class="card-header">Dashboard</div>
				<div class="card-body">
					@if (session('status'))
						<div class="alert alert-success">
							{{ session('status') }}
						</div>
					@endif

					<div class="p-3 mb-2 bg-gradient-primary text-white">.bg-gradient-primary</div>
					<div class="p-3 mb-2 bg-gradient-secondary text-white">.bg-gradient-secondary</div>
					<div class="p-3 mb-2 bg-gradient-success text-white">.bg-gradient-success</div>
					<div class="p-3 mb-2 bg-gradient-danger text-white">.bg-gradient-danger</div>
					<div class="p-3 mb-2 bg-gradient-warning text-dark">.bg-gradient-warning</div>
					<div class="p-3 mb-2 bg-gradient-info text-white">.bg-gradient-info</div>
					<div class="p-3 mb-2 bg-gradient-light text-dark">.bg-gradient-light</div>
					<div class="p-3 mb-2 bg-gradient-dark text-white">.bg-gradient-dark</div>


					<form class="">
						<select class="form-control selectpicker">
							<option>Mustard</option>
							<option>Ketchup</option>
							<option>Relish</option>
						</select>

						<input type="text" placeholder="teste input" class="form-control">

						<label class="sr-only" for="inlineFormInputName2">Name</label>
						<input type="text" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2" placeholder="Jane Doe">

						<label class="sr-only" for="inlineFormInputGroupUsername2">Username</label>
						<div class="input-group mb-2 mr-sm-2">
							<div class="input-group-prepend">
								<div class="input-group-text">R$</div>
							</div>
							<input type="text" class="form-control" id="inlineFormInputGroupUsername2" placeholder="Username">
							<div class="input-group-append">
								<div class="input-group-text">,00</div>
							</div>
						</div>
						<button type="submit" class="btn btn-primary mb-2">Submit</button>
					</form>
					<div class="row">
						<div class="col">
							<div class="form-label-group">
								<input type="text" class="form-control" id="prod_name3" name="prod_name3" placeholder="Nome" v-model="product.name" required>
								<label for="prod_name3">Nome</label>
							</div>
						</div>
						<div class="col">
							<div class="input-group">
								<div class="input-group-prepend">
									<div class="input-group-text">R$</div>
								</div>
								<div class="form-label-group form-control">
									<input type="text" id="prod_name" name="prod_name" placeholder="Nome" v-model="product.name" required>
									<label for="prod_name">Nome</label>
								</div>
								<div class="input-group-append">
									<div class="input-group-text">,00</div>
								</div>
							</div>
						</div>
					</div>
<div class="row">
	<div class="col">
		<div class="form-label-group">
			<select class="form-control float-label-select" id="prod_category" name="prod_category" v-model="product.category_id">
				<option value="1">1</option>
				<option value="2">2</option>
				<option value="3">3</option>
			</select>
			<label for="prod_category">Categoria</label>
		</div>
	</div>
</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/app/menu.blade.php
<nav class="navbar navbar-expand-md navbar-light navbar-laravel">
	<div class="container">
		@if(Auth::user())
			<a class="navbar-brand" href="{{ route('home') }}">{{ config('app.name', 'Laravel') }}</a>
		@else
			<a class="navbar-brand" href="{{ route('index') }}">{{ config('app.name', 'Laravel') }}</a>
		@endif
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<!-- Left Side Of Navbar -->
			<ul class="navbar-nav mr-auto">
			</ul>

			<!-- Right Side Of Navbar -->
			<ul class="navbar-nav ml-auto">
				<!-- Authentication Links -->
				@guest
					<li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
					<li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
				@else

					<li><a class="nav-link" href="{{ route('products.shop') }}">Shop</a></li>
					@if(Auth::user()->role == USER_ROLES_ADMIN) 
						<li><a class="nav-link" href="{{ route('products.index') }}">Produtos</a></li>
					@endif
					<li><a class="nav-link" href="{{ route('users.index') }}">Usuários</a></li>
					<li class="nav-item dropdown">
						<a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
							{{ Auth::user()->name }} <span class="caret"></span>
						</a>

						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
							<a class="dropdown-item" href="{{ route('logout') }}"
							   onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
								{{ __('Logout') }}
							</a>

							<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
								@csrf
							</form>
						</div>
					</li>
					<li><a class="nav-link" href="{{ route('orders.cart') }}"><i class="fas fa-shopping-cart"></i></span></a></li>
				@endguest
			</ul>
		</div>
	</div>
</nav>