routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('register', 'UsersController@create')->name('register');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

// Default Routes
Route::get('/', 'ProductsController@shop')->name('index');
Route::get('home', 'HomeController@appIndex')->name('home');
Route::get('status/all', 'StatusController@all')->name('status.all');
Route::get('categories/all', 'CategoriesController@all')->name('categories.all');

Route::get('products/desc/{id}', 'ProductsController@desc')->name('products.desc');
Route::get('products/shop', 'ProductsController@shop')->name('products.shop');
Route::get('products/find/{id}', 'ProductsController@find')->name('products.find');
Route::get('products/all', 'ProductsController@all')->name('products.all');

Route::post('users', 'UsersController@store')->name('users.store');

// Admin Routes
Route::group(['middleware' => ['auth', 'can:access-admin']], function () {
	// Attributes
	Route::get('attributes/create/{product_id}', 'AttributesController@create')->name('attributes.create');
	Route::get('attributes/edit/{id}', 'AttributesController@edit')->name('attributes.edit');

	// Categories
	Route::get('categories/edit/{id}', 'CategoriesController@edit')->name('categories.edit');

	// Products
	Route::put('products/image/pull/{id}/{index}', 'ProductsController@pullImage')->name('products.image.pull');
	Route::put('products/image/push/{id}/{index}', 'ProductsController@pushImage')->name('products.image.push');
	Route::post('products/image/{id}', 'ProductsController@uploadImage')->name('products.image.upload');
	Route::delete('products/image/{id}/{index}', 'ProductsController@deleteImage')->name('products.image.delete');

	// Resources
	Route::resource('attributes', 'AttributesController')->except(['index','show','create','edit']);
	Route::resource('categories', 'CategoriesController')->only(['create','store','update']);
	Route::resource('products', 'ProductsController');
});

// Authenticated Routes
Route::group(['middleware' => ['auth']], function () {
	Route::get('users/find/{id}', 'UsersController@find')->name('users.find');
	Route::get('users/all', 'UsersController@all')->name('users.all');

	// Orders
	Route::get('orders/home/{id}', 'OrdersController@home')->name('orders.home');
	Route::get('orders/cart', 'OrdersController@cart')->name('orders.cart');
	Route::get('orders/current', 'OrdersController@current')->name('orders.current');
	Route::get('orders/delivery', 'OrdersController@delivery')->name('orders.delivery');
	Route::get('orders/payment', 'OrdersController@payment')->name('orders.payment');
	Route::get('orders/payment/billet', 'OrdersController@billet')->name('orders.payment.billet');
	Route::get('orders/payment/card', 'OrdersController@card')->name('orders.payment.card');
	Route::get('orders/checkout', 'OrdersController@checkout')->name('orders.checkout');
	Route::get('orders/checkout/success/{id}', 'OrdersController@success')->name('orders.checkout.success');
	Route::get('orders/card/create', 'OrdersController@cardCreate')->name('orders.card.create');
	Route::get('orders/find/{id}', 'OrdersController@find')->name('orders.find');
	Route::get('orders/form/address', 'OrdersController@formAddress')->name('orders.form.address');
	Route::get('orders/delivery/cost', 'OrdersController@calcDeliveryCost')->name('orders.delivery.cost');
	Route::put('orders/item/method', 'OrdersController@changeItemMethod')->name('orders.item.method.change');
	Route::put('orders/item/installment', 'OrdersController@changeItemInstallment')->name('orders.item.installment.change');
	Route::post('orders/checkout', 'OrdersController@postCheckout')->name('orders.checkout.post');
	Route::post('orders/item/{product_id}', 'OrdersController@addItem')->name('orders.item.add');
	Route::post('orders/address', 'OrdersController@storeAddress')->name('orders.address.store');
	Route::post('orders/payment/select_card', 'OrdersController@selectCard')->name('orders.payment.select_card');

	// Items
	Route::post('items/store', 'ItemsController@store')->name('items.store');
	Route::post('items/increase/{id}', 'ItemsController@increase')->name('items.increase');
	Route::post('items/decrease/{id}', 'ItemsController@decrease')->name('items.decrease');
	Route::delete('items/destroy/{id}', 'ItemsController@destroy')->name('items.destroy');

	// Cards
	Route::get('cards/all', 'CardsController@all')->name('cards.all');
	Route::get('cards/edit/{id}', 'CardsController@edit')->name('cards.edit');

	// Resources
	Route::resource('cards', 'CardsController')->only(['create','store','update']);
	Route::resource('orders', 'OrdersController');
	Route::resource('users', 'UsersController')->except('store');
});

app/Models/Attribute.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class Attribute.
 *
 * @package namespace App\Models;
 */
class Attribute extends Model implements Transformable {
    use TransformableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'value', 'product_id'];

}

app/Http/Controllers/AttributesController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\AttributeRepository;

class AttributesController extends Controller{

	public function __construct(AttributeRepository $repository){
		$this->repository = $repository;
		$this->names = [
			'plural' => 'attributes',
			'singular' => 'attribute',
			'pt_plural' => 'atributos',
			'pt_singular' => 'atributo',
			'pt_gender' => 'o',
			'base_blades' => 'attributes'
		];
	}

	/**
	 * Disponible methods from Trait.
	 */
	use ControllerTrait {
		ControllerTrait::trait_edit as edit;
		ControllerTrait::trait_all as all;
		ControllerTrait::trait_store as store;
		ControllerTrait::trait_update as update;
		ControllerTrait::trait_destroy as destroy;
	}

	/**
	 * Show the form for create resource.
	 */
	public function create($product_id) {
		return view('app.attributes.create', compact('product_id'));
	}

}

resources/views/app/attributes/_form.blade.php
<div class="row">
	<div class="col-sm-6">
		<div class="form-label-group">
			<input type="text" class="form-control" id="att_name" name="att_name" placeholder="Nome" v-model="attribute.name" required>
			<label for="att_name">Nome</label>
		</div>
	</div>
	<div class="col-sm-6">
		<div class="form-label-group">
			<input type="text" class="form-control" id="att_value" name="att_value" placeholder="Valor" v-model="attribute.value" required>
			<label for="att_value">Valor</label>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
		<div class="form-group text-center">
			<button type="submit" class="btn btn-success float-right" title="Salvar">{!! ICONS_OK !!}</i></button>
			<button type="button" class="btn btn-outline-danger center" title="Excluir" @click.prevent="submitFormDeleteAttribute" v-if="attribute.id > 0">{!! ICONS_REMOVE !!}</i></button>
			<button type="button" class="btn btn-danger float-left closeFancybox" title="Cancelar">{!! ICONS_CANCEL !!}</i></button>
		</div>
	</div>
</div>

resources/views/app/attributes/create.blade.php
<div>
	<div id="attributeCreateApp">
		<h2 class="page-title">Atributo <small> | Cadastro Atributo</small></h2>
		<form action="{{ route('attributes.store') }}" id="formCreateAttribute" data-prefix="att">
			@include('app.attributes._form')
		</form>
	</div>

	<script type="text/javascript">
		new Vue({
			el: '#attributeCreateApp',
			data: {
				attribute: {
					product_id: '{{ $product_id }}'
				}
			},
			mounted: function(){
				var self = this;
				$("#formCreateAttribute").cValidate({
					data: self.attribute
				});
			}
		});
	</script>
</div>

resources/views/app/attributes/edit.blade.php
<div>
	<div id="attributeEditApp">
		<h2 class="page-title">Atributo <small> | Edição de Atributo</small></h2>
		<form action="{{ route('attributes.update', [$attribute->id]) }}" id="formEditAttribute" method="PUT" data-prefix="att">
			@include('app.attributes._form')
		</form>
	</div>

	<script type="text/javascript">
		new Vue({
			el: '#attributeEditApp',
			data: {
				attribute: {!! $attribute->toJson() !!}
			},
			mounted: function(){
				var self = this;
				$("#formEditAttribute").cValidate({
					data: self.attribute
				});
			},
			methods:{
				submitFormDeleteAttribute: function (){ 
					var token = {'_token': "{{ csrf_token() }}"};
					$.delete('{{ route('attributes.destroy', [$attribute->id]) }}', token, function(data) {
						toastr.success('Atributo removido com sucesso');
						parent.jQuery.fancybox.close();
					});
				}
			}
		});
	</script>
</div>