routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('register', 'UsersController@create')->name('register');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

// Default Routes
Route::get('/', 'ProductsController@shop')->name('index');
Route::get('home', 'HomeController@appIndex')->name('home');
Route::get('status/all', 'StatusController@all')->name('status.all');
Route::get('categories/all', 'CategoriesController@all')->name('categories.all');

Route::get('products/desc/{id}', 'ProductsController@desc')->name('products.desc');
Route::get('products/shop', 'ProductsController@shop')->name('products.shop');
Route::get('products/find/{id}', 'ProductsController@find')->name('products.find');
Route::get('products/all', 'ProductsController@all')->name('products.all');

Route::post('users', 'UsersController@store')->name('users.store');

// Admin Routes
Route::group(['middleware' => ['auth', 'can:access-admin']], function () {
	// Attributes
	Route::get('attributes/create/{product_id}', 'AttributesController@create')->name('attributes.create');
	Route::get('attributes/edit/{id}', 'AttributesController@edit')->name('attributes.edit');

	// Categories
	Route::get('categories/edit/{id}', 'CategoriesController@edit')->name('categories.edit');

	// Products
	Route::put('products/image/pull/{id}/{index}', 'ProductsController@pullImage')->name('products.image.pull');
	Route::put('products/image/push/{id}/{index}', 'ProductsController@pushImage')->name('products.image.push');
	Route::post('products/image/{id}', 'ProductsController@uploadImage')->name('products.image.upload');
	Route::delete('products/image/{id}/{index}', 'ProductsController@deleteImage')->name('products.image.delete');

	// Resources
	Route::resource('attributes', 'AttributesController')->except(['index','show','create','edit']);
	Route::resource('categories', 'CategoriesController')->only(['create','store','update']);
	Route::resource('products', 'ProductsController');
});

// Authenticated Routes
Route::group(['middleware' => ['auth']], function () {
	Route::get('users/find/{id}', 'UsersController@find')->name('users.find');
	Route::get('users/all', 'UsersController@all')->name('users.all');

	// Orders
	Route::get('orders/home/{id}', 'OrdersController@home')->name('orders.home');
	Route::get('orders/cart', 'OrdersController@cart')->name('orders.cart');
	Route::get('orders/current', 'OrdersController@current')->name('orders.current');
	Route::get('orders/delivery', 'OrdersController@delivery')->name('orders.delivery');
	Route::get('orders/payment', 'OrdersController@payment')->name('orders.payment');
	Route::get('orders/payment/billet', 'OrdersController@billet')->name('orders.payment.billet');
	Route::get('orders/payment/card', 'OrdersController@card')->name('orders.payment.card');
	Route::get('orders/checkout', 'OrdersController@checkout')->name('orders.checkout');
	Route::get('orders/checkout/success/{id}', 'OrdersController@success')->name('orders.checkout.success');
	Route::get('orders/card/create', 'OrdersController@cardCreate')->name('orders.card.create');
	Route::get('orders/find/{id}', 'OrdersController@find')->name('orders.find');
	Route::get('orders/form/address', 'OrdersController@formAddress')->name('orders.form.address');
	Route::get('orders/delivery/cost', 'OrdersController@calcDeliveryCost')->name('orders.delivery.cost');
	Route::put('orders/item/method', 'OrdersController@changeItemMethod')->name('orders.item.method.change');
	Route::put('orders/item/installment', 'OrdersController@changeItemInstallment')->name('orders.item.installment.change');
	Route::post('orders/checkout', 'OrdersController@postCheckout')->name('orders.checkout.post');
	Route::post('orders/item/{product_id}', 'OrdersController@addItem')->name('orders.item.add');
	Route::post('orders/address', 'OrdersController@storeAddress')->name('orders.address.store');
	Route::post('orders/payment/select_card', 'OrdersController@selectCard')->name('orders.payment.select_card');

	// Items
	Route::post('items/store', 'ItemsController@store')->name('items.store');
	Route::post('items/increase/{id}', 'ItemsController@increase')->name('items.increase');
	Route::post('items/decrease/{id}', 'ItemsController@decrease')->name('items.decrease');
	Route::delete('items/destroy/{id}', 'ItemsController@destroy')->name('items.destroy');

	// Cards
	Route::get('cards/all', 'CardsController@all')->name('cards.all');
	Route::get('cards/edit/{id}', 'CardsController@edit')->name('cards.edit');

	// Resources
	Route::resource('cards', 'CardsController')->only(['create','store','update']);
	Route::resource('orders', 'OrdersController');
	Route::resource('users', 'UsersController')->except('store');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;

/**
 * Class User.
 *
 * @package namespace App\Models;
 */
class User extends Authenticatable implements Transformable{
	use Notifiable;
	use TransformableTrait;

	protected $fillable = [
		'id',
		'name',
		'username',
		'password',
		'email',
		'cp',
		'phone1',
		'phone2',
		'gender',
		'birthdate',
		'zipcode',
		'state',
		'city',
		'district',
		'street',
		'number',
		'complement',
		'status',
		'role',
		'parent_id'
	];

	protected $hidden = [
		'password', 'remember_token',
	];

	//protected $appends = ['search'];

	public function getSearchAttribute(){
		return "$this->id - $this->name [$this->city]";
	}
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\UserRepository;
use Auth;

class UsersController extends Controller {

	/**
	 * UsersController constructor.
	 */
	public function __construct(UserRepository $repository) {
		$this->repository = $repository;
		$this->names = [
			'plural' => 'users',
			'singular' => 'user',
			'pt_plural' => 'usuários',
			'pt_singular' => 'usuário',
			'pt_gender' => 'o',
			'base_blades' => 'users'
		];
	}

	/**
	 * Disponible methods from Trait.
	 */
	use ControllerTrait {
		ControllerTrait::trait_edit as edit;
		ControllerTrait::trait_store as store;
		ControllerTrait::trait_update as update;
	}

	/**
	 * Display a listing of the resource.
	 */
	public function index() {
		$this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
		if(Auth::user()->role == USER_ROLES_ADMIN){
			$users = $this->repository->all();
		}else{
			$users = $this->repository->findWhere(['parent_id' => Auth::user()->id]);
		}
		return view('app.users.index', compact('users'));
	}

	/**
	 * Display the specified resource.
	 */
	public function show($id) {
		$user = $this->repository->find($id);
		if(Auth::user()->role != USER_ROLES_ADMIN && $user->parent_id != Auth::user()->id){
			return view('app.errors.permission');
		}else{
			return view('app.users.show', compact('user'));
		}
		
	}

	/**
	 * Show the form for create resource.
	 */
	public function create() {
		$users = $this->repository->all();
		return Auth::user() ? view('app.users.create', compact('users')) : view('auth.register', compact('users'));
	}

	/**
	 * Return list with all users.
	 */
	public function all(){
		if(Auth::user()->role != USER_ROLES_ADMIN){
			return $this->repository->findWhere(['parent_id' => Auth::user()->id]);
		}else{
			return $this->repository->all();
		}
	}
}

resources/views/app/users/_form.blade.php
@if(Auth::user() && (Auth::user()->role == USER_ROLES_ADMIN || Auth::user()->role == USER_ROLES_SELLER))
	<div class="row">
		<div class="col">
			<div class="form-group">
				<div class="btn-group btn-group-toggle border rounded d-flex" role="group" data-toggle="buttons" style="width: 100%;">
					@if(Auth::user()->role == USER_ROLES_ADMIN)
						<label class="btn btn-light w-100" :class="{active : user.role == '{{ USER_ROLES_ADMIN }}'}">
							<input type="radio" name="usr_role" table="user" field="role" autocomplete="off" v-model="user.role" value="{{ USER_ROLES_ADMIN }}" required> Admin
						</label>
					@endif
					<label class="btn btn-light w-100" :class="{active : user.role == '{{ USER_ROLES_SELLER }}'}">
						<input type="radio" name="usr_role" table="user" field="role" autocomplete="off" v-model="user.role" value="{{ USER_ROLES_SELLER }}" required> Vendedor
					</label>
					<label class="btn btn-light w-100" :class="{active : user.role == '{{ USER_ROLES_PARTNER }}'}">
						<input type="radio" name="usr_role" table="user" field="role" autocomplete="off" v-model="user.role" value="{{ USER_ROLES_PARTNER }}" required> Parceiro
					</label>
				</div>
			</div>
		</div>
	</div>
@endif
<div class="row">
	<div class="col-xs-12 col-md-6">
		<div class="form-label-group">
			<input type="text" class="form-control" id="usr_name" name="usr_name" placeholder="Nome" v-model="user.name" required>
			<label for="name">Nome</label>
		</div>
	</div>
	<div class="col-xs-12 col-sm-6 col-md-3">
		<div class="form-label-group">
			<input type="text" class="form-control" id="usr_cp" name="usr_cp" placeholder="CPF/CNPJ" v-model="user.cp" v-mask="['###.###.###-##', '##.###.###/####-##']" required>
			<label for="usr_cp">CPF/CNPJ</label>
		</div>
	</div>
	<div class="col-xs-12 col-sm-6 col-md-3">
		<div class="form-label-group">
			<input type="text" class="form-control" autocomplete="off" id="usr_username" name="usr_username" placeholder="Login" v-model="user.username" required minlength="6" maxlength="20">
			<label for="usr_username">Login</label>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-6">
		<div class="form-label-group">
			<input type="date" class="form-control" id="usr_birthdate" name="usr_birthdate" placeholder="Data de Nascimento" v-model="user.birthdate" required>
			<label for="usr_birthdate">Data de Nascimento</label>
		</div>
	</div>
	<div class="col-xs-12 col-sm-6">
		<div class="form-group">
			<div class="btn-group btn-group-toggle border rounded d-flex" role="group" data-toggle="buttons" style="width: 100%; height: 49px;">
				<label class="btn btn-light w-100" :class="{active : user.gender == 'male'}" style="padding-top:12px;">
					<input type="radio" name="usr_gender" table="user" field="gender" autocomplete="off" v-model="user.gender" value="male" required>Masculino
				</label>
				<label class="btn btn-light w-100" :class="{active : user.gender == 'female'}" style="padding-top:12px;">
					<input type="radio" name="usr_gender" table="user" field="gender" autocomplete="off" v-model="user.gender" value="female" required>Feminino
				</label>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-6">
		<div class="form-label-group">
			<input type="email" class="form-control" id="usr_email" name="usr_email" placeholder="E-mail" v-model="user.email" required>
			<label for="usr_email">E-mail</label>
		</div>
	</div>
	<div class="col">
		<div class="form-label-group">
			<input type="text" class="form-control" id="usr_phone1" name="usr_phone1" placeholder="Fone 1" v-model="user.phone1" v-mask="['(##)####-####', '(##)#####-####']" required>
			<label for="usr_phone1">Fone 1</label>
		</div>
	</div>
	<div class="col">
		<div class="form-label-group">
			<input type="text" class="form-control" id="usr_phone2" name="usr_phone2" placeholder="Fone 2" v-model="user.phone2" v-mask="['(##)####-####', '(##)#####-####']">
			<label for="usr_phone2">Fone 2</label>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-6 col-sm-3">
		<div class="form-label-group">
			<input type="text" class="form-control" id="usr_zipcode" name="usr_zipcode" placeholder="CEP" v-model="user.zipcode"  v-mask="['#####-###']" required>
			<label for="usr_zipcode">CEP</label>
		</div>
	</div>
	<div class="col-xs-6 col-sm-3">
		<div class="form-label-group">
			<input type="text" class="form-control" id="usr_district" name="usr_district" placeholder="Bairro" v-model="user.district" required>
			<label for="usr_district">Bairro</label>
		</div>
	</div>
	<div class="col-xs-8 col-sm-4">
		<div class="form-label-group">
			<input type="text" class="form-control" id="usr_city" name="usr_city" placeholder="Cidade" v-model="user.city" required>
			<label for="usr_city">Cidade</label>
		</div>
	</div>
	<div class="col-xs-4 col-sm-2">
		<div class="form-label-group">
			<input type="text" class="form-control" id="usr_state" name="usr_state" placeholder="UF" v-model="user.state" v-mask="['AA']" required>
			<label for="usr_state">UF</label>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-6">
		<div class="form-label-group">
			<input type="text" class="form-control" id="usr_street" name="usr_street" placeholder="Endereço" v-model="user.street" required>
			<label for="usr_street">Endereço</label>
		</div>
	</div>
	<div class="col-sm-2">
		<div class="form-label-group">
			<input type="text" class="form-control" id="usr_number" name="usr_number" placeholder="Nº" v-model="user.number" v-mask="['######']" required>
			<label for="usr_number">Nº</label>
		</div>
	</div>
	<div class="col-sm-4">
		<div class="form-label-group">
			<input type="text" class="form-control" id="usr_complement" name="usr_complement" placeholder="Complemento" v-model="user.complement" >
			<label for="usr_complement">Complemento</label>
		</div>
	</div>
</div>
@if(!Auth::user())
	<div class="row" v-if="user.role != '{{ USER_ROLES_ADMIN }}'">
		<div class="col">
			<div class="form-label-group">
				<input type="text" class="form-control" id="usr_parent_name" name="usr_parent_name" placeholder="Responsável">
				<label for="usr_parent_id">Responsável</label>
			</div>
			<input type="hidden" id="usr_parent_id" v-model="user.parent_id">
		</div>
	</div>
@endif
<div class="row">
	<div class="col-sm-12">
		<div class="form-group">
			<button type="submit" class="btn btn-success float-right" title="Salvar">{!! ICONS_OK !!}</i></button>
			<button type="button" class="btn btn-danger float-left closeFancybox" title="Cancelar">{!! ICONS_CANCEL !!}</i></button>
		</div>
	</div>
</div>

resources/views/app/users/create.blade.php
<div>
	<div id="userCreateApp">
		<h2 class="page-title">Usuário <small> | Cadastro de novo Usuário</small></h2>
		<form action="{{ route('users.store') }}" id="formCreateUser" data-prefix="usr">
			@include('app.users._form')
		</form>
	</div>

	<script type="text/javascript">
		var userCreateApp = new Vue({
			el: '#userCreateApp',
			data: {
				user: {
					street: '',
					district: '',
					city: '',
					state: '',
					role: 'partner',
				},
				parents: [
					@foreach($users as $user)
						{!! '{ id: '.$user->id.', search: "'.$user->search.'"},' !!}
					@endforeach
				]
			},
			mounted: function(){
				var self = this;
				$("label.btn").click(function(event) {
					var child = $(this).children().first();
					self[child.attr('table')][child.attr('field')] = child.val();
				});
				$("#usr_parent_name").cAutocomplete({
					items: self.parents, 
					searchAttr: "search", 
					idAttr: "id",
					idField: "#usr_parent_id"
				});
				$("#formCreateUser").cValidate({
					data: self.user,
					unmask: ['phone1', 'phone2'],
					success: 'Usuário criado com sucesso!',
					error: 'Falha ao criar usuário!',
					redirect: {!! !Auth::user() ? "'".route('login')."'" : 'false' !!},
				});
			},
			watch:{
				'user.zipcode': function(val){
					var self = this;
					if(val.length == 9){
						setAddressData(val, self.user);
					}
				}
			}
		});
	</script>
</div>

resources/views/app/users/edit.blade.php
<div>
	<div id="userEditApp">
		<h2 class="page-title">Usuário <small> | Edição de Usuário</small></h2>
		<form action="{{ route('users.update', [$user->id]) }}" id="formEditUser" method="PUT" data-prefix="usr">
			@include('app.users._form')
		</form>
	</div>

	<script type="text/javascript">
		new Vue({
			el: '#userEditApp',
			data: {
				user: {!! $user->toJson() !!}
			},
			mounted: function(){
				var self = this;
				$("label.btn").click(function(event) {
					var child = $(this).children().first();
					self[child.attr('table')][child.attr('field')] = child.val();
				});
				$("#formEditUser").cValidate({
					data: self.user,
					unmask: ['phone1', 'phone2'],
					success: 'Usuário atualizado com sucesso!',
					error: 'Falha ao atualizar usuário!',
				});
			},
			watch:{
				'user.zipcode': function(val){
					var self = this;
					if(val.length == 9){
						setAddressData(val, self.user);
					}
				}
			}
		});
	</script>
</div>

resources/views/app/users/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="page-title">
		<h3>
			Usuários | <small class="text-muted">Listagem de Usuários cadastrados</small>
			<button type="button" class="btn btn-sm btn-primary float-right" title="Novo Usuário" onclick="openFormUser()">{!! ICONS_ADD !!}</button>
		</h3>
	</div>
	<nav aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
			<li class="breadcrumb-item active" aria-current="page">Usuários</li>
		</ol>
	</nav>
	<div class="row justify-content-center">
		<div class="col">
			<div class="card">
				<div class="card-body">
					<table id="table-users" class="table table-striped table-hover table-pointer">
						<thead>
							<tr>
								<th>Nome</th>
								<th>E-mail</th>
								<th>Nascimento</th>
								<th>Categoria</th>
								<th>Status</th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>Nome</th>
								<th>E-mail</th>
								<th>Nascimento</th>
								<th>Categoria</th>
								<th>Status</th>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		$(document).ready(function() {
			$('#table-users').DataTable({
				ajax: {
					url: "{{ route('users.all') }}",
					dataSrc: ""
				},
				columns: [
					{ data: function(data){ return filters.name(data.name); }},
					{ data: function(data){ return filters.default(data.email); }},
					{ data: function(data){ return filters.date(data.birthdate); }},
					{ data: function(data){ return filters.default(data.role); }},
					{ data: function(data){ return filters.yn(data.status); }}
				],
				processing: true,
				order: [],
				fnRowCallback: function( row, data, index, indexFull ) {
					$(row).on('click', function(evt) {
						window.open("{{ route('users.show', ['']) }}/"+data.id, evt.ctrlKey ? '_blank' : '_self');
					});
				}
			});
		});

		function openFormUser(){
			$.fancybox.open({
				src: '{{ route('users.create') }}',
				type: 'ajax',
				opts: { 
					clickOutside: false,
					clickSlide: false,
					afterClose : function(){
						$('#table-users').DataTable().ajax.reload(null, false); 
					},
				}
			});
		}
	</script>
@endsection

resources/views/app/users/show.blade.php
@extends('layouts.app')

@section('content')
	<div id="userShowApp">
		<div class="page-title">
			<h3>
				Usuários | <small class="text-muted">Descrição do usuário</small>
				<button type="button" class="btn btn-sm btn-primary float-right" title="Alterar Cadastro" @click="openFormEditUser()">{!! ICONS_EDIT !!}</button>
			</h3>
		</div>
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
				<li class="breadcrumb-item"><a href="{{ route('users.index') }}">Usuários</a></li>
				<li class="breadcrumb-item active" aria-current="page">{{ $user->name }}</li>
			</ol>
		</nav>
		<div class="row justify-content-center">
			<div class="col-sm-3">
				<div class="card">
					<div class="card-body">
						<div class="row justify-content-center">
							<div class="col-10">
								@if(count(Illuminate\Support\Facades\Storage::files($path = env('FILES_PATH_USERS')."/".$user->id."/")) > 0)
									<img src="{{ env('FILES_PATH_USERS').'/'.$user->id.'/' }}" class="img-fluid img-thumbnail rounded-circle">
								@else
									<img v-if="user.gender == 'female'" src="{{ DEFAULT_IMAGE_USERS_FEMALE }}" class="img-fluid img-thumbnail border-2 rounded-circle" :class="[user.status == 1 ? 'border-success' : 'border-danger']">
									<img v-else src="{{ DEFAULT_IMAGE_USERS_MALE }}" class="img-fluid img-thumbnail border-2 rounded-circle" :class="[user.status == 1 ? 'border-success' : 'border-danger']">
								@endif
							</div>
						</div>
						<div class="row">
							<div class="col">
								<hr>
							</div>
						</div>
						<div class="row">
							<div class="col">
								<h5 class="text-center">[ @{{ user.id | default }} ] @{{ user.name | name }}<br><small>[ @{{ user.role | name }} ] @{{ user.username }}<br></small></h5>
							</div>
						</div>
						<div class="row">
							<div class="col">
								<hr>
							</div>
						</div>
						<div class="row">
							<div class="col">
								<label class="label-plaintext label-sm" for="usr_email">E-mail:</label>
								<p class="form-control-plaintext" id="usr_email">@{{ user.email | default }}</p>
							</div>
						</div>
						<div class="row">
							<div class="col">
								<label class="label-plaintext label-sm" for="usr_phone">Telefones:</label>
								<p class="form-control-plaintext" id="usr_phone">@{{ user.phone1 | phone }} / @{{ user.phone2 | phone }}</p>
							</div>
						</div>
						<div class="row">
							<div class="col">
								<label class="label-plaintext label-sm" for="usr_birthdate">Data de Nascimento:</label>
								<p class="form-control-plaintext" id="usr_birthdate">@{{ user.birthdate | date }}</p>
							</div>
						</div>
						<div class="row">
							<div class="col">
								<label class="label-plaintext label-sm" for="usr_city">Bairro - Cidade/UF:</label>
								<p class="form-control-plaintext" id="usr_city">@{{ user.district | default }} - @{{ user.city | default }}/@{{ user.state | default }}</p>
							</div>
						</div>
						<div class="row">
							<div class="col">
								<label class="label-plaintext label-sm" for="usr_zipcode">CEP:</label>
								<p class="form-control-plaintext" id="usr_zipcode">@{{ user.zipcode | cep }}</p>
							</div>
						</div>
						<div class="row">
							<div class="col">
								<label class="label-plaintext label-sm" for="usr_street">Endereço:</label>
								<p class="form-control-plaintext" id="usr_street">@{{ user.street | default }}, @{{ user.number | default }}</p>
							</div>
						</div>
						<div class="row">
							<div class="col">
								<label class="label-plaintext label-sm" for="usr_complement">Complemento:</label>
								<p class="form-control-plaintext" id="usr_complement">@{{ user.complement | default }}</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-sm-9">
				<div class="card">
					<div class="card-body">
						<div class="form-controler">
							<label>Imagens:</label>
							<div class="files-input">
								<input id="fileupload" type="file" name="files[]" data-url="server/php/" multiple>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		new Vue({
			el: '#userShowApp',
			data: {
				user: {!! $user->toJson() !!}
			},
			mounted: function(){
				var self = this;
				validaForm("#formImageUpload", function() {
					var formData = new FormData($('#formImageUpload')[0]);
					$.ajax({
						url: "{ { route('users.image.upload', [$user->id]) }}",
						type: 'POST',
						success: completeHandler = function(data) { 
							self.reloadData();
						},
						data: formData,
						cache: false,
						contentType: false,
						processData: false,
						async: true
					}, 'json');
				});
				$('#fileInput').change(function(event) {
					if($('#fileInput').val()){
						$('#formImageUpload').submit();
					}
				});
			},
			methods:{
				reloadData: function (){
					var self = this;
					$.get('{{ route('users.find', [$user->id]) }}', function(data) {
						if(data.error){
							toastr.error('Falha ao atualizar usuário!');
						}else{
							self.user = data;
						}
					});
				},
				openFormEditUser: function(){
					var self = this;
					$.fancybox.open({
						src: '{{ route('users.edit', [$user->id]) }}',
						type: 'ajax',
						opts: { 
							clickOutside: false,
							clickSlide: false,
							afterClose : function(){
								self.reloadData(); 
							},
						}
					});
				},
				openFormImage: function(){
					$('#fileInput').click();
				}
			},
			filters: filters
		});
	</script>
@endsection